# Generated by Django 4.0.5 on 2022-06-11 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probid', models.CharField(max_length=200)),
                ('statement', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('difficulty', models.CharField(default='easy', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probid', models.CharField(max_length=200)),
                ('verdict', models.CharField(max_length=200)),
                ('submittedat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probid', models.CharField(max_length=200)),
                ('input', models.CharField(max_length=200)),
                ('output', models.CharField(max_length=200)),
            ],
        ),
    ]
